### PR TITLE
Use sync.Map to avoid using constructor NewObserver, minor bugfix

### PR DESCRIPTION
**Pull request by andviro**
Hi there! The main change is using sync.Map to make Observer structure ready to use without any initialization calls. Also purged uuid dependency in favor of atomic id increment. Last, but not least - fixed potential race condition when trying to write to subscription in goroutine while its channel may be already closed by the cancel func.

### CODE REVIEW

**Comment by leonsteinhaeuser** [comment]
@andviro thanks for providing these changes. I will have a closer look at them in the next few days.

**Comment by leonsteinhaeuser** [comment]
@andviro I took a closer look at it, it is simple and very useful to banish the unnecessary dependencies and initialization steps. I would ask you to add a few tests and change the sample in the _example folder and in the README.

If you agree, I would like to merge/rebase your branch with the upstream changes from main.

**Comment by andviro** [comment]
sure, will do as soon as I can

**Comment by andviro** [comment]
Hello again! Added separate example for Handle[T], hope it'll do

**Comment by leonsteinhaeuser** [comment]
I saw the following message in a report:

```
Check failure on line 8 in observer_test.go
GitHub Actions / unit tests

no required module provides package golang.org/x/sync/errgroup; to add it:
```

I think it needs to be added to the go.mod.

**Comment by andviro** [comment]
uh, sorry. Forgot that I was working in workspace mode (I actively use the library in some private projects). Fixed this, hopefully

**Review by leonsteinhaeuser — APPROVED** [review]
Thank you for all your changes.

**Comment by leonsteinhaeuser** [comment]
I just wanted to let you know that I have released a new version of this library. Feel free to update your dependency.

**Comment by andviro** [comment]
great, thanks for your work!

**Pull request merged**
